server:
  port: 3001
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CarRentalDB
      username: bilge
      password: bilge!123
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
redis:
  host: localhost
  port: 6379