server:
  port: 80
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RewritePath=/(?<segment>.*), /api/v1/$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:3001
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: profile-service
          uri: http://localhost:3002
          predicates:
            - Path=/profile/**
          filters:
            - name: CircuitBreaker
              args:
                name: profileCircuitBreaker
                fallbackUri: forward:/fallback/profile

        - id: mail-service
          uri: http://localhost:3000
          predicates:
            - Path=/mail/**
          filters:
            - name: CircuitBreaker
              args:
                name: mailCircuitBreaker
                fallbackUri: forward:/fallback/mail

