server:
  port: 3000
  error:
    include-message: always
    include-binding-errors: always
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: hevalcanaslan@gmail.com
    password: mfxv rqbt kqno puii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true